package umb;
/*
 * umbMain.java
 *
 * Created on February 13, 2002, 11:14 AM
 */

/**
 *
 * @author  chris
 */
public class umbMain extends javax.swing.JFrame {
    private javax.swing.DefaultListModel theList = new javax.swing.DefaultListModel(); // for the JList
    private umbPrefs thePrefs = new umbPrefs();
    private java.lang.Thread theFilterThread;
    private umbFilter theFilter;
    
    /** Creates new form umbMain */
    public umbMain() {
        initComponents();
        // jList1.setModel(theList);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();
        jList1 = new javax.swing.JList();
        jPanel5 = new javax.swing.JPanel();
        jPanel51 = new javax.swing.JPanel();
        jPanel52 = new javax.swing.JPanel();
        jPanel53 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jPanel1.setLayout(new java.awt.BorderLayout(0, 5));

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButton1.setText("Preferences");
        jPanel3.add(jButton1);

        jButton2.setText("Start");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel3.add(jButton2);

        jPanel1.add(jPanel3, java.awt.BorderLayout.SOUTH);

        jPanel9.setLayout(new java.awt.BorderLayout(0, 5));

        jLabel1.setText("UMB - Unwanted Mail Blocker v0.1");
        jPanel9.add(jLabel1, java.awt.BorderLayout.NORTH);

        jLabel2.setText("Copyright (c) 2002 by Christopher Wiegand of Aurora, Colorado, USA");
        jPanel9.add(jLabel2, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel9, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new java.awt.BorderLayout(0, 5));

        jPanel2.add(jProgressBar1, java.awt.BorderLayout.NORTH);

        jLabel3.setText("...");
        jPanel2.add(jLabel3, java.awt.BorderLayout.SOUTH);

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "theList" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jPanel2.add(jList1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel5, java.awt.BorderLayout.WEST);

        getContentPane().add(jPanel51, java.awt.BorderLayout.EAST);

        getContentPane().add(jPanel52, java.awt.BorderLayout.NORTH);

        getContentPane().add(jPanel53, java.awt.BorderLayout.SOUTH);

        pack();
    }//GEN-END:initComponents
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Add your handling code here:
        if (jButton2.getText().equalsIgnoreCase("Start")) {
            // start session
            jButton2.setText("Stop");
            theFilter = new umbFilter(this,thePrefs);
            if (theFilterThread != null) {
                theFilterThread.stop();
            }
            theFilterThread = new java.lang.Thread(theFilter);
            theFilterThread.start();
        } else {
            // stop session
            jButton2.setText("Start");
            if (theFilterThread != null) {
                theFilterThread.stop();
                theFilterThread = null;
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    public void threadDone() {
        // called from thread..
        jButton2.setText("Start");
        if (theFilterThread != null) {
            theFilterThread.stop();
            theFilterThread = null;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        if (args.length > 0) {
            int i = 0;
            for (i = 0; i < args.length; i = i + 1) {
                if (args[i].equalsIgnoreCase("--defaults")) {
                    java.util.prefs.Preferences prefs; // get prefs for THIS package
                    prefs = java.util.prefs.Preferences.userRoot().node("/Wiegand/UnwantedMailBlocker");
                    
                    prefs.put("Addresses","christopherwiegand@hotmail.com,test@wiegand.cx");
                    prefs.put("Profiles","Test Profile");
                    prefs.putBoolean("DebugLog",true);
                    prefs = prefs.node("Test Profile");
                    prefs.put("POP3Server","pop.server");
                    prefs.put("Username","username");
                    prefs.put("Password","hushitsasecret");
                    prefs.put("SMTPServer","daspost.myisp.es");
                } // if (args[i]
            } // for i
        } // if args.length
        
        new umbMain().show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel53;
    private javax.swing.JPanel jPanel52;
    private javax.swing.JPanel jPanel51;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JList jList1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    
    public void addInfoLine(String s) {
        theList.addElement(s);
        this.jList1.repaint();
        this.repaint();
    }
    
    public void updateStatus(int iValue, int iMax, String sText) {
        this.jProgressBar1.setMaximum(iMax);
        this.jProgressBar1.setValue(iValue);
        this.jProgressBar1.repaint();
        this.jLabel3.setText(sText);
        this.jLabel3.repaint();
        this.repaint();
    }
}
